-- =============================================
--          -== Plugin Configs ==-
-- =============================================
require("plugins/config/lsp")
require("plugins/config/lspsaga")
require("plugins/config/autopairs")
require("plugins/config/cmp")
require("plugins/config/bufferline")
require("plugins/config/dashboard")
require("plugins/config/other")
require("plugins/config/lualine")
require("plugins/config/indentline")
require("plugins/config/toggleterm")
require("plugins/config/colorizer")
require("plugins/config/treesitter")
require("plugins/config/telescope")
require("plugins/config/trouble")
require("plugins/config/gitsigns")
require("plugins/config/nvimtree")
require("plugins/config/misc")
