#!/bin/env sh
# 0xNexn Bash/Zsh Aliases

[ -d /mnt/files/NOTES ] && alias nv="vim /mnt/files/NOTES"

# Utils
alias vim="nvim"
alias v="nvim"
alias wiki="vim -c VimwikiIndex"
alias ed="ed -p '➡ '"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias python="python2.7"
alias py="python3"
alias rss="newsboat"
alias music="ncmpcpp"
alias r="ranger"
alias mail="neomutt"
alias irssi=irssi --config="$XDG_CONFIG_HOME/irssi/config" --home="$XDG_DATA_HOME/irssi"
alias tp="trash"
alias tl="trash-list"
alias tr="trash-restore"
alias t="tldr"
alias clashgui="$HOME/.local/bin/clash/cfw"
alias tb="nc termbin.com 9999"
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias yarn="yarn --use-yarnrc $HOME/.yarn/yarnrc"

# Changing "ls" to "exa"
if [ -n "$(command -v exa)" ]; then
    alias ls="exa --color=always --group-directories-first"
    alias ll="exa -l --color=always --group-directories-first"
    alias la="exa -la --color=always --group-directories-first"
fi

# Clipboard
# npm install -g clipboard-cli
alias cb="clipboard"

# h4x0r m4n Stuff :D
alias up="python3 -m http.server"
alias upphp="php --server=127.0.0.1:80"


# confirm before overwriting something
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# bare git repo alias for dotfiles
alias cg="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias lcg="lazygit --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias cgs="git --git-dir=$HOME/.dotfiles --work-tree=$HOME status"
alias cgd="git --git-dir=$HOME/.dotfiles --work-tree=$HOME status -s | awk '{ print \$2}' | fzf | xargs -I {} git --git-dir=$HOME/.dotfiles --work-tree=$HOME diff {}"
alias cga="git --git-dir=$HOME/.dotfiles --work-tree=$HOME add"

# the terminal rickroll
alias rr="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"

# typo
alias "cd.."="cd .."
alias "cd."="cd .."
alias claer="clear"

alias arduino-cli="arduino-cli --config-file $XDG_CONFIG_HOME/arduino15/arduino-cli.yaml"
alias svn="svn --config-dir $XDG_CONFIG_HOME/subversion"
